examples/validate_schema.cpp, include/ddwaf.h, src/PWAdditive.cpp, src/PWAdditive.hpp, src/PWProcessor.cpp, src/PWRet.cpp, src/PWRet.hpp, src/PowerWAFInterface.cpp, tests/TestAdditive.cpp, tests/TestInterface.cpp, tests/TestParser.cpp, tests/TestProcessor.cpp, tests/TestRegressions.cpp, tests/TestRetriever.cpp, tests/TestSchema.cpp, tests/TestTransform.cpp, tests/rule_processor/TestLibInjectionSQL.cpp, tests/rule_processor/TestLibInjectionXSS.cpp, tests/test.h
- Removal of `ddwaf_result.action` due to being equivalent to the return value of `ddwaf_run`.
- Removal of `DDWAF_ERR_TIMEOUT`.
- Addition of `ddwaf_result.timeout` to signal when there has been a timeout at any point during the run.
- Rearranged items in `ddwaf_result` to reduce struct size.
In case of timeout, the WAF will return a verdict (`DDWAF_GOOD`, `DDWAF_BLOCK`, `DDWAF_MONITOR`) and set the flag if there has been a timeout during the operation regardless of when it happens.
=> ddwaf_result: add timeout flag and remove action field

CMakeLists.txt
The Ninja generator does not like `cd` in the middle of a command and fails to execute the last step of the `libddwaf_static` target. This PR simplifies the offending command.
=> Avoid using cd in add_custom_command

.github/workflows/build.yml, src/PWAdditive.cpp, src/rule.hpp
The MacOS toolchain has incomplete support for C++17 on 10.9 (which is the minimum version required for distributing Python binaries on MacOS). This PR builds the MacOS libraries for this target and workarounds the unsupported method.
=> Fix MacOS compilation errors for 10.9

src/PWProcessor.cpp, tests/TestRegressions.cpp, tests/yaml/regressions2.yaml
Multiple matches accumulate while processing a flow, causing the reported match to contain duplicate matches.
=> Fix duplicate matches accumulated per flow

src/PWRetriever.cpp, src/PWTransformer.cpp, src/PowerWAF.cpp, src/PowerWAFInterface.cpp, src/log.hpp, src/object.cpp, src/parser/parser_v1.cpp, src/parser/parser_v2.cpp
Fix an integer overflow in `DDWAF_LOG_HELPER`. This is likely unexploitable since `malloc(INT32_MIN)` should return `NULL` which causes an early abort.
Also solves a bunch of implicit casts warnings.
=> Fix an integer overflow in the log macro

CMakeLists.txt, fuzzing/src/ddwaf_interface.cpp, include/ddwaf.h, src/PWAdditive.cpp, src/PWAdditive.hpp, src/PWProcessor.cpp, src/PWProcessor.hpp, src/PWRet.cpp, src/PWRet.hpp, src/PWRetriever.cpp, src/PWRetriever.hpp, src/PowerWAF.cpp, src/PowerWAF.hpp, src/obfuscator.cpp, src/obfuscator.hpp, src/validator.cpp, src/validator.hpp, tests/TestAdditive.cpp, tests/TestObfuscator.cpp, tests/TestProcessor.cpp, tests/TestRetriever.cpp, tests/TestRule.cpp, tests/TestValidator.cpp, tests/test.h, tests/yaml/obfuscator.yaml
WAF Obfuscator provided as a separate class, for now this simply provides a verdict on whether obfuscation should be done, but the objective would be to have an intermediate event structure which can then be directly obfuscated instead. As of now this introduces an inefficiency in that matches can be discarded after they have been created, if other conditions do not match, so the obfuscation would've been unnecessary (the same applies to generating JSON at that stage). This inefficiency will be addressed with the intermediate event structure.
This also introduces a slight refactoring of the object limits, for now the `max_string_length` limit is not being used but it will be in the near future.
=> WAF Obfuscator

src/PWAdditive.cpp
This PR makes it optional to keep a reference on the ddwaf_run parameters when no free function was specified. As a result, it should use less memory per context.
=> Only take params ownership when needed

examples/verify_rule.cpp, third_party/libinjection/src/libinjection_sqli.c, third_party/libinjection/src/libinjection_sqli.h
Make libinjection more tolerant of backticks, since they're often used in SQL injections.
For instance, introduce detection for 
```
1` or "1" = "1"
```
=> Make libinjection look for backticks

include/ddwaf.h, src/interface.cpp, src/rule_data_dispatcher.hpp, src/waf.hpp, tests/interface_test.cpp, tests/waf_test.cpp
Add a function to obtain the require rule data IDs. This provides the WAF user with the ability to filter and discard unnecessary rule IDs before passing them to the WAF.
=> Add function to obtain required rule data IDs

docker/libddwaf/aarch64/Dockerfile
Add the missing libunwind.a file to the aarch64 archive of the libc++.
=> linux/aarch64: add missing libunwind.a artefact

CMakeLists.txt
Add strip invocation on libddwaf.a for linux and darwin in release builds.
libddwaf.a is used by the Go tracer to link with the WAF and stripping makes for a better user experience.
This emerged from https://github.com/DataDog/dd-trace-go/issues/1478.
=> Strip libddwaf.a for darwin/linux release

.github/workflows/build.yml, third_party/CMakeLists.txt
We are currently compiling libddwaf on `macos-latest` where it appears some new symbols have been introduced in the libstdc++ which are absent for macos 10.15's libstdc++. 
Related to https://github.com/DataDog/dd-trace-go/issues/1478
=> Experiment building libddwaf on the oldest available macos target

src/exclusion/object_filter.cpp, src/exclusion/object_filter.hpp, src/iterator.cpp, src/object.cpp, src/utils.h, tests/object_filter_test.cpp, tests/path_trie_test.cpp, tests/test_utils.hpp, validator/ruleset.yaml, validator/tests/216_rule40_keypath_exclusion_with_glob.yaml
This PR introduces support for the glob key path component (`*`) within object filters. This has been implemented by allowing the trie traverser to keep track and descend through many nodes at the same time.  In addition, the use of the glob also allows for arrays within the key path.
=> Support for glob component and arrays on object filter

include/ddwaf.h, src/context.hpp, src/interface.cpp, src/waf.cpp, src/waf.hpp, tests/interface_test.cpp, tests/waf_test.cpp
Ensure contexts share ownership of the handle and extend its lifetime when the user calls `ddwaf_destroy` while contexts are still in use.
=> Handle lifetime extension

src/ruleset_builder.cpp, tests/interface_test.cpp
Allow rule overrides by tag to operate on rules already overridden by ID, while still maintaining the priority of the override by ID.
=> Relax rule override restrictions

src/rule_processor/exact_match.cpp, src/rule_processor/ip_match.cpp, tests/rule_processor/exact_match.cpp, tests/rule_processor/ip_match_test.cpp, third_party/radixlib/radixlib.c, third_party/radixlib/radixlib.h
This PR enforces the longest expiration for `ip_match` and `exact_match` operators.
Additionally, it adds support for IP network matching with expiration. Basically, if `2.0.0.0/16` is blocked forever but `2.2.2.2` is blocked for 5 minutes, `2.2.2.2` should still be blocked after 5 minutes.
=> Longest rule data expiration takes precedence for `ip_match` and `exact_match` operators

src/clock.cpp
This PR adds support to load the vDSO version of `clock_gettime` for aarch64 as described in [`man vdso`](https://man7.org/linux/man-pages/man7/vdso.7.html).
=> clock: add vdso support for aarch64

src/PWTransformer.cpp, src/condition.cpp, src/condition.hpp, src/parser/parser_v1.cpp, src/parser/parser_v2.cpp, tests/collection_test.cpp, tests/condition_test.cpp, tests/context_test.cpp, tests/input_filter_test.cpp, tests/integration/conditions/test.cpp, tests/integration/conditions/yaml/global_transformer.yaml, tests/integration/conditions/yaml/input_transformer.yaml, tests/integration/conditions/yaml/overlapping_transformers.yaml, tests/rule_filter_test.cpp, tests/rule_test.cpp
Support per-input transformers with the schema of the following example:
```
"inputs": [
{
"address": "http.client_ip",
"key_path": [],
"transformers": []
}
],
=> Support for per-input transformers

src/parser/parser_v2.cpp, tests/input_filter_test.cpp, tests/rule_filter_test.cpp, tests/yaml/exclude_one_rule_with_condition_and_transformers.yaml
Exclusion filter conditions currently don't support transformers, this change introduces support specifically for per-input transformers.
=> Per-input transformers support on exclusion filter conditions

src/collection.cpp, src/collection.hpp, src/context.cpp, src/context.hpp, src/event.cpp, src/event.hpp, src/exclusion/rule_filter.cpp, src/exclusion/rule_filter.hpp, src/parser/parser_v2.cpp, src/parser/specification.hpp, src/ruleset_builder.cpp, tests/context_test.cpp, tests/parser_v2_rule_filters.cpp, tests/rule_filter_test.cpp, tests/yaml/monitor_bypass_precedence.yaml, tests/yaml/monitor_one_rule.yaml, validator/main.cpp, validator/runner.cpp, validator/tests/exclusions/rule_filter/conditional/009_rule1_monitored_through_condition.yaml, validator/tests/exclusions/rule_filter/conditional/010_rule_no_exclusions.yaml, validator/tests/exclusions/rule_filter/conditional/ruleset.yaml, validator/tests/exclusions/rule_filter/unconditional/009_rule9_rule_monitored_by_id.yaml, validator/tests/exclusions/rule_filter/unconditional/010_rule10_rule_monitored_by_tags.yaml, validator/tests/exclusions/rule_filter/unconditional/ruleset.yaml
This PR adds support for rule filter monitor and bypass (default) modes:
- In monitor mode, rules are still evaluated but actions (`on_match`) are not provided as part of the result.
- Bypass mode  is the current (and default) behaviour in which a rule is simply skipped from evaluation.
=> Rule filter bypass / monitor mode support

fuzzing/src/object_builder.cpp, include/ddwaf.h, libddwaf.def, src/expression.cpp, src/iterator.cpp, src/matcher/base.hpp, src/matcher/equals.hpp, src/object.cpp, src/parameter.cpp, src/parameter.hpp, src/parser/parser_v2.cpp, src/utils.hpp, tests/TestInterface.cpp, tests/integration/matchers/test.cpp, tests/integration/matchers/yaml/equals.yaml, tests/interface_test.cpp, tests/key_iterator_test.cpp, tests/matcher/equals_test.cpp, tests/object_test.cpp, tests/parameter_test.cpp, tests/test_utils.cpp, tests/transformer/manager_test.cpp, tests/value_iterator_test.cpp, validator/utils.cpp
Add support for `float` and `null` types, while also allowing `invalid` within containers.
Breaking changes:
- `ddwaf_object` now has one more field in the union for doubles called `f64`
- `ddwaf_object_*_force` are now the standard, so the `_force` suffix has been removed.
- `ddwaf_object_signed` and `ddwaf_object_unsigned` have now been renamed to `ddwaf_object_string_from_*`
- Not breaking but two new types have been introduced, `DDWAF_OBJ_FLOAT` and `DDWAF_OBJ_NULL`
=> Float and null type support

.github/workflows/test.yml
Coverage was broken after moving to gcc-12, this PR fixes it and also introduces the generation of HTML coverage since codecov is often hitting github rate limits.
=> Fix coverage

src/generator/base.hpp, src/generator/extract_schema.cpp, src/generator/extract_schema.hpp, src/parser/parser.hpp, src/parser/parser_v2.cpp, src/parser/specification.hpp, src/processor.cpp, src/processor.hpp, src/ruleset.hpp, src/ruleset_builder.cpp, src/ruleset_builder.hpp, src/scanner.hpp, tests/context_test.cpp, tests/generator/extract_schema_test.cpp, tests/integration/processors/ruleset/processor_with_scanner_by_id.json, tests/integration/processors/ruleset/processor_with_scanner_by_tags.json, tests/integration/processors/test.cpp, tests/mkmap_test.cpp, tests/parser_v2_input_filters_test.cpp, tests/parser_v2_rule_filters_test.cpp, tests/parser_v2_rules_override_test.cpp, tests/parser_v2_scanner_test.cpp, tests/processor_test.cpp, tests/scanner_test.cpp, tests/test_utils.hpp
This PR introduces a new high-level feature called `scanner` which is used by the schema extraction generator to attempt to infer the nature and semantics of key-value pairs which, in this context, is known as classification. Scanners are meant to be a generic tool for processors, for example an obfuscation processor could use scanners to determine what to obfuscate in a more configurable manner.
The main changes introduced in this PR:
- Scanner class: it's an extremely simple class, which takes an ID and two matchers, one for keys and another one for values. The caller can then provide keys and values to obtain a verdict.
- The schema extraction generator has been updated to evaluate scanners on each string and add metadata to the schema.
- The parser can now parse scanners and also …
=> Scanners for schema scalar classification

src/collection.cpp, src/collection.hpp, src/context.hpp, src/exclusion/input_filter.cpp, src/exclusion/input_filter.hpp, src/exclusion/rule_filter.cpp, src/exclusion/rule_filter.hpp, src/expression.cpp, src/expression.hpp, src/generator/base.hpp, src/matcher/base.hpp, src/parser/parser_v1.cpp, src/parser/parser_v2.cpp, src/parser/specification.hpp, src/processor.hpp, src/rule.cpp, src/rule.hpp, src/ruleset.hpp, src/ruleset_builder.cpp, src/ruleset_builder.hpp, src/scanner.hpp, src/waf.hpp, tests/collection_test.cpp, tests/context_test.cpp, tests/mkmap_test.cpp, tests/parser_v2_scanner_test.cpp, tests/ruleset_test.cpp, tests/scanner_test.cpp, tools/verify_ruleset.cpp
For convenience and reducing characters, I introduced a  `ptr` typedef (using declaration) on certain classes which were typically used as a `shared_ptr`. Over time the use of this `ptr` typedef was extended to other classes, some as `shared_ptr` and some as `unique_ptr`, which has made it very difficult to understand the underlying pointer type.  This PR removes them to make the underlying pointer type more explicit.
=> Remove ptr typedefs

.github/workflows/build.yml
Update nuget packaging script to include the new linux musl binaries
=> Update nuget packaging to use new musl linux binaries

src/generator/extract_schema.cpp, src/scanner.hpp, tests/generator/extract_schema_test.cpp, tests/scanner_test.cpp
- Propagate ancestor keys for scanner evaluation during schema extraction.
- Fail scanner evaluation if key is invalid and a matcher is available.
=> [APPSEC-11574] Schema extraction scanners: reduce false positives on arrays

src/exclusion/object_filter.cpp, src/exclusion/object_filter.hpp, tests/object_filter_test.cpp
The WAF offers naive support for duplicate addresses across calls to `ddwaf_run`, however object filters do not support this feature due to the way they cache targets. This change allows the object filter to efficiently cache targets whilst providing support for duplicate addresses.
Related Jira: [APPSEC-11672]
[APPSEC-11672]: https://datadoghq.atlassian.net/browse/APPSEC-11672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Duplicate address support on input/object filters

include/ddwaf.h, libddwaf.def, perf/main.cpp, src/interface.cpp, src/parser/parser_v2.cpp, src/processor.hpp, src/ruleset.hpp, src/ruleset_builder.cpp, src/ruleset_builder.hpp, src/ruleset_info.cpp, src/ruleset_info.hpp, tests/integration/diagnostics/test.cpp, tests/integration/diagnostics/yaml/input_filter.yaml, tests/integration/diagnostics/yaml/rule_data.yaml, tests/integration/processors/test.cpp, tests/interface_test.cpp, tests/parser_v2_processors_test.cpp, tests/processor_test.cpp, tools/verify_ruleset.cpp
This PR introduces information regarding addresses to the diagnostics for each of the different features. This includes both required and optional addresses, for example:
```
"processors": {
"loaded": [
"processor-001"
],
"failed": [],
"errors": {},
"addresses": {
"required": [ ... ],
"optional": [ ... ]
}
},
```
This allows the WAF user to distinguish which addresses they actually need to provide (required) from those which are opportunistically used (optionals) . It also allows distinguishing addresses which are used in potentially disabled features, for example, the processors section would provide insights into the addresses used for schema extraction:
- Required refers to the condition addresses.
- Optional refers to the mappings used to generate schemas, these are not "required" to …
=> Address diagnostics

docker/libddwaf/build/Dockerfile, docker/libddwaf/sysroot/Toolchain.cmake.aarch64, docker/libddwaf/sysroot/Toolchain.cmake.armv7, docker/libddwaf/sysroot/Toolchain.cmake.i386, docker/libddwaf/sysroot/Toolchain.cmake.x86_64, tests/integration/matchers/test.cpp, tests/integration/processors/test.cpp, tests/integration/regressions/test.cpp, tests/integration/transformers/test.cpp
Attempt to reduce binary size:
* Unused section elimination: `-ffunction-sections -fdata-sections -Wl,--gc-sections -Wl,--discard-all ` 
* Identical code folding: `-Wl,--icf=safe -Wl,--print-icf-sections`
This PR also changes the toolchain file used to allow changes without rebuild.
Using `-flto` seems to cause some issues with the static libraries.
Results for `libddwaf.so`:
```
+---------+---------+---------+------------+
| Arch    | 1.14.0  | 1.15.0  | Difference |
+---------+---------+---------+------------+
| Aarch64 | 2523712 | 2127104 | 15.72%     |
| x86_64  | 2595272 | 2195224 | 15.41%     |
| armv7   | 2100652 | 1725020 | 17.88%     |
| i386    | 2302492 | 1908688 | 17.10%     |
+---------+---------+---------+------------+
| Average | 2380532 | 1989009 | 16.53%     | …
```
=> Reduce linux binary size and fix some flaky tests

.github/workflows/benchmark.yml, .github/workflows/test.yml, CHANGELOG.md
Rule writers use some existing WAF tools to validate new rules, this change adds a CI job to verify that the tools are building as expected.
=> Build tools on CI to avoid breaking tool users

src/parser/parser_v2.cpp, tools/common/utils.cpp, tools/waf_runner.cpp
WAF Runner Improvements:
- Run on multiple inputs with `--input <json input> [<json input>..]`
- Run on multiple configs with `--ruleset <json/yaml file> [<json/yaml file>..]`
- Print events, actions and derivatives
=> Improvements to WAF Runner utility

benchmark/main.cpp, benchmark/object_generator.cpp, benchmark/object_generator.hpp, benchmark/scenarios/float_equals_matcher.json, benchmark/scenarios/ruleset_1.10.0.json, benchmark/scenarios/signed_equals_matcher.json, benchmark/scenarios/unsigned_equals_matcher.json
- Fix some issues on valid test generation.
- Removed "mixed" tests.
- Added fixed-size tests with the nomenclature: `random.<container depth>x<container size>.<string length>
=> Fix benchmark variances

src/vendor/libinjection/src/libinjection_sqli.c, src/vendor/libinjection/src/libinjection_sqli.h, tests/matcher/is_sqli_test.cpp
libinjection interpret invalid sequences (such as words starting after a number without separators, which is causing false positives.
=> SECRES-1649 - Address a libinjection false positive

benchmark/scenarios/phrase_match_matcher_enforce_word_boundary.json, fuzzing/scripts/build_corpus.py, src/matcher/phrase_match.cpp, src/matcher/phrase_match.hpp, src/parser/parser_v2.cpp, src/utils.hpp, tests/integration/matchers/test.cpp, tests/integration/matchers/yaml/phrase_match.yaml, tests/matcher/phrase_match_test.cpp, tests/utils_test.cpp, validator/tests/rules/operators/phrase_match/001_rule1_pm_match.yaml, validator/tests/rules/operators/phrase_match/002_rule1_pm_no_match.yaml, validator/tests/rules/operators/phrase_match/003_rule2_pm_word_bound_match.yaml, validator/tests/rules/operators/phrase_match/004_rule2_pm_word_bound_no_match.yaml, validator/tests/rules/operators/phrase_match/ruleset.yaml
Add option to phrase match operator to enforce word boundaries on all matches.
```
- operator: phrase_match
parameters:
inputs: [ ... ]
list: [ ... ]
options:
enforce_word_boundary: true
```
Some notable things to consider:
- When `enforce_word_boundary` is set to true, the algorithm will always try to find the longest match to increase the likelihood of word boundaries.
- If the match found doesn't have word boundaries around it, no other match is provided.
=> Phrase match: enforce word boundary option

.github/workflows/build.yml, docker/libddwaf/smoketest/gnu_rhel6/Dockerfile, docker/libddwaf/sysroot/Dockerfile
* Add a smoke test for old RHEL 6-based distros.
* Add `-D_LIBCPP_HAS_NO_C11_ALIGNED_ALLOC=1` to libc++ CFLAGS to ensure it doesn't use `aligned_alloc` and use a fallback. This is the only missing symbol on old RHEL 6.
=> Add support for old glibc (e.g. RHEL 6)

.github/workflows/build.yml
Use new arm64 runners for aarch64 and armv7 builds, this doesn't provide much currently since we are using cross-compilation toolchains, however the slowest smoke test went from 2 minutes to 20 seconds so it's still valuable.
=> Attempt to build libddwaf on arm64 runner

UPGRADING.md, src/ruleset_builder.cpp, tests/integration/actions/test.cpp, tests/integration/actions/yaml/invalid_actions.yaml
If the `actions` is provided with an incompatible type (i.e. anything but an array), the resulting action mapper is a `nullptr` rather than a valid structure. This later on can cause a segmentation fault on `ddwaf_run`.
=> Fix mishandling invalid actions key type

.github/workflows/fuzz.yml, README.md, src/glibc-compat/math.c
- Use the improved version of `ceilf` for amd64 from https://github.com/DataDog/nginx-datadog/pull/65
- Add some badges to the readme
- Run fuzzer on schedule and on push to master
=> Use SSE4.1 ceilf when available and add badges to readme

.github/workflows/fuzz.yml, LICENSE-3rdparty.csv, cmake/objects.cmake, fuzzer/sha256/corpus/.gitignore, fuzzer/sha256/src/main.cpp, src/sha256.cpp, src/sha256.hpp, tests/sha256_test.cpp
This PR introduces a class to compute the sha256 digest, the code is based on the [openssl](https://github.com/openssl/openssl/blob/140540189c67ba94188165b1144fdfb5b248bc02/crypto/sha/sha256.c#L124) implementation. At first, the objective is to use this hash for request fingerprinting purposes, however it could be used for other purposes:
- As a processor generator, in order to produce a hash of part of the request, in a similar fashion to a fingerprint although more targeted.
- As a transformer, to match obfuscated data.
=> SHA256 hash based on OpenSSL

src/indexer.hpp, src/mkmap.hpp, src/ruleset.hpp, src/ruleset_builder.cpp, tests/interface_test.cpp, tests/mkmap_test.cpp, tests/waf_test.cpp, tests/yaml/ruleset_with_disabled_rule.yaml
This PR introduces a small change which consists in simply not adding disabled rules to the final ruleset. This reduces the number of rules that need to be iterated and it also helps ensuring that `ddwaf_known_addresses` always returns a list of usable addresses, which in turn can be used to identify enabled / disabled exploit prevention rules given their unique resource address.
Related Jira: [APPSEC-53751]
[APPSEC-53751]: https://datadoghq.atlassian.net/browse/APPSEC-53751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Skip disabled rules when generating ruleset

src/collection.cpp, src/context.cpp, src/event.cpp, src/event.hpp, src/exclusion/common.hpp, src/exclusion/rule_filter.cpp, src/exclusion/rule_filter.hpp, src/parser/exclusion_parser.cpp, src/parser/specification.hpp, src/ruleset_builder.cpp, tests/parser_v2_rule_filters_test.cpp, tests/rule_filter_test.cpp, tests/yaml/bypass_custom_precedence.yaml, tests/yaml/exclude_with_custom_action.yaml, tests/yaml/exclude_with_custom_action_and_condition.yaml, tests/yaml/exclude_with_nonblocking_action.yaml, tests/yaml/exclude_with_unknown_action.yaml, tests/yaml/monitor_custom_precedence.yaml, validator/tests/exclusions/rule_filter/unconditional/010_rule10_rule_monitored_by_tags.yaml, validator/tests/exclusions/rule_filter/unconditional/011_rule11_rule_custom_action_by_id.yaml, validator/tests/exclusions/rule_filter/unconditional/012_rule11_rule_not_blocking.yaml, validator/tests/exclusions/rule_filter/unconditional/ruleset.yaml
This PR introduces support for custom exclusion filter actions, limited to rule filters only. The filter custom action allows overriding the "blocking" (i.e. block, redirect, monitor) action of a rule if the exclusion filter is evaluated positively. For example, when the following filter matches the given IP, `rule 1` is set to `block`:
```yaml
exclusions:
- id: 1
rules_target:
- rule_id: 1
conditions:
- operator: ip_match
parameters:
inputs:
- address: http.client_ip
list:
- 192.168.0.1
on_match: block
```
The precedence of rule filter actions is still `bypass > monitor > custom`.
This feature is one of the two required for suspicious attacker blocking.
Related Jira: [APPSEC-53545]
[APPSEC-53545]: https://datadoghq.atlassian.net/browse/APPSEC-53545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …
=> Custom rule filter actions

src/parser/expression_parser.cpp, src/parser/parser_v1.cpp, src/parser/rule_parser.cpp, src/utils.hpp, tests/parser_v1_test.cpp, tests/parser_v2_rules_test.cpp, tests/yaml/invalid_too_many_transformers_v1.yaml
This PR introduces a limit to the number of transformers that can be used on a single input. This limit has been arbitrarily set to 10 transformers in order to account for future requirements and is currently not user configurable.
The limit applies to transformers in a rule:
```json
{
"id": "rule-xxx-yyy",
"name": "rule with transformers",
"tags": { ... },
"conditions": [ ... ],
"transformers": [ ... ]
}
```
As well as transformers applied to a single input:
```json
{
"id": "rule-xxx-yyy",
"name": "rule with transformers",
"tags": { ... },
"conditions": [
{
"operator": "match_regex",
"parameters": {
"inputs": [
{
"address": "arg2",
"key_path": [
"y"
],
"transformers": [ ... ]
}
],
"regex": ".*"
}
}
]
}
```
Related Jira: [APPSEC-53552]
[APPSEC-53552]: …
=> Limit the number of transformers per rule or input

src/parser/actions_parser.cpp, src/uri_utils.cpp, tests/parser_v2_actions_test.cpp, tests/uri_utils_test.cpp
Extra validations for redirect actions:
- Valid status codes are now 301, 302, 303 or 307
- The `location` must now:
-  Be a valid URL
- If it contains a scheme, it must be either `http` or `https`
- if it doesn't, it must be an absolute-path reference starting with `/`
The URI parser has been updated to support:
- Fragments and query on URLs without authority 
- Network-path references
- Absolute-path references
- Relative-path references are not yet supported
Related Jira: [APPSEC-53568]
[APPSEC-53568]: https://datadoghq.atlassian.net/browse/APPSEC-53568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Validate redirection location and restrict status codes

src/obfuscator.hpp, tests/obfuscator_test.cpp, tools/waf_runner.cpp
This PR updates the default obfuscator regex, used if the user-provided regexes are unusable. A test has also been added to ensure some expected patterns are detected.
Related Jiras: [APPSEC-53957]
[APPSEC-53957]: https://datadoghq.atlassian.net/browse/APPSEC-53957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update default obfuscator regex

src/event.cpp, src/parser/rule_override_parser.cpp, src/parser/specification.hpp, src/rule.hpp, src/ruleset_builder.cpp, tests/interface_test.cpp, tests/parser_v2_rules_override_test.cpp
This PR introduces support for adding tags to a rule through rule overrides. The schema of `rules_override` has been updated to support a new `tags` field, which is a map containing the new tags which must be added to a given set of rules. The set of tags to add must not overlap with the set of default tags already available on the rule; any overlapping tag will be ignored. For example:
```json
"rules_override": [
{
"rules_target": [
{
"tags": {
"confidence": "1"
}
}
],
"tags": {
"policy": "custom-policy-1"
}
}
]
```
Tags will only be used for reporting purposes and won't impact other overrides or exclusion filters targeting a tag set.
Related Jira: [APPSEC-11810]
[APPSEC-11810]: https://datadoghq.atlassian.net/browse/APPSEC-11810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZ …
=> Rule override for adding tags

.github/workflows/fuzz.yml, fuzzer/CMakeLists.txt, fuzzer/common/common.hpp, fuzzer/http_endpoint_fingerprint/corpus/.gitignore, fuzzer/http_endpoint_fingerprint/src/main.cpp, fuzzer/http_header_fingerprint/corpus/.gitignore, fuzzer/http_header_fingerprint/src/main.cpp, fuzzer/http_network_fingerprint/corpus/.gitignore, fuzzer/http_network_fingerprint/src/main.cpp, fuzzer/session_fingerprint/corpus/.gitignore, fuzzer/session_fingerprint/src/main.cpp
Fuzzers to validate fingerprints, currently each fuzzer generates suitable data for each fingerprint type, including known headers. As an improvement, random object types could be included on maps.
=> Fingerprint fuzzer

src/rule.hpp, src/ruleset.hpp, tests/integration/context/test.cpp, tests/integration/context/yaml/same-type-different-module.yaml
This PR introduces a very small change to ensure two rules with different `module` but same `type` aren't grouped in the same collection. This ensures that `type` collisions don't prevent RASP rules from being evaluated.
=> Split collections by module

src/condition/sqli_detector.cpp, src/condition/sqli_detector.hpp, tests/sqli_detector_internals_test.cpp
If an injection is within a comment, it can be matched as a false positive if the comment is not the first or last token in the resource.  To avoid these false positives, we must ensure that the comment itself was part of the injection and / or more than one token was injected.
Related Jiras: [APPSEC-54410]
[APPSEC-54410]: https://datadoghq.atlassian.net/browse/APPSEC-54410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix false positive on SQLi EOL comments

src/condition/match_iterator.hpp, src/condition/shi_detector.cpp, src/condition/sqli_detector.cpp, src/condition/ssrf_detector.cpp, tests/condition/lfi_detector_test.cpp, tests/condition/match_iterator_test.cpp, tests/condition/shi_detector_test.cpp, tests/condition/sqli_detector_internals_test.cpp, tests/condition/sqli_detector_test.cpp, tests/condition/ssrf_detector_test.cpp
This PR introduces an iterator to iterate through all possible matches of a parameter within a given resource. This expands the number of detections that one could perform on a single resource. This is now being used in SQLi, SHi and SSRF.
=> Expand detections per parameter

include/ddwaf.h, src/semver.hpp, tools/verify_rule.cpp
The `verify_rule` utility loads a single rule, which means that if the rule is incompatible due to the new versioning mechanism, the resulting WAF instance will be invalid due to a lack of valid rules. This change adds a check for min and max version within the `verify_rule` utility.
=> Support (min|max)_version on verify_rule utility

src/condition/ssrf_detector.cpp, src/condition/ssrf_detector.hpp, tests/unit/condition/ssrf_detector_test.cpp
This PR adds extra checks to the SSRF heuristic to prevent matching the scheme when it's the only injection performed, as it's not a likely injection and the match itself is prone to false positives. 
Related Jira: [APPSEC-55879]
[APPSEC-55879]: https://datadoghq.atlassian.net/browse/APPSEC-55879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Prevent scheme matches in isolation

fuzzer/http_endpoint_fingerprint/src/main.cpp, src/processor/fingerprint.cpp, src/processor/fingerprint.hpp, tests/integration/processors/fingerprint/test.cpp, tests/unit/processor/fingerprint_test.cpp
This PR changes the endpoint fingerprint to allow for a missing query parameter; this can happen when the request includes no query parameters.
Related Jira: [APPSEC-56486]
[APPSEC-56486]: https://datadoghq.atlassian.net/browse/APPSEC-56486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Change endpoint fingerprint query parameter to optional

.github/workflows/build.yml, schema/actions.json, schema/diagnostics.json, schema/events.json, schema/schema.json, tests/common/gtest_utils.cpp, tests/common/gtest_utils.hpp, tests/integration/diagnostics/v2/test.cpp, tests/integration/events/schema/test.cpp, third_party/CMakeLists.txt, tools/validate_schema.cpp
This PR updates the output object schemas and validates them on integration tests. In addition, it also adds all schemas to the release artifacts so they can be easily referenced by external repositories.
Related Jira: [APPSEC-57250]
[APPSEC-57250]: https://datadoghq.atlassian.net/browse/APPSEC-57250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update schemas and tests to include validation

UPGRADING.md
`ddwaf_builder_remove_config` example is wrong since it has two extra non-expected arguments.
=> Fix `ddwaf_builder_remove_config` example

schema/actions.json, src/configuration/actions_parser.cpp, src/serializer.cpp, tests/common/gtest_utils.cpp, tests/common/gtest_utils.hpp, tests/integration/actions/test.cpp, tests/integration/context/test.cpp, tests/integration/exclusion/rule_filter/test.cpp, tests/integration/interface/waf/test.cpp, tests/integration/rules/custom_rules/test.cpp, tests/unit/serializer_test.cpp, validator/tests/exclusions/rule_filter/conditional/010_rule_no_exclusions.yaml, validator/tests/rules/actions/001_rule1_match_with_actions.yaml
This PR introduces an ID to the `block_request` and `redirect_request` action parameters, as well as the underlying event. This allows the WAF caller to link an event which resulted in a blocking action to the response provided to the actual application user (.e.g by displaying the ID in the HTML). 
The generated ID is a UUIDv4 and it'll be included in the result as follows:
```yaml
events:
- rule:
...
on_match:
- block
rule_matches: ...
block_id: cfe3688e-993d-11f0-b50d-c785d6db0d0e
actions:
block_request:
grpc_status_code: 10
type: auto
status_code: 403
block_id: cfe3688e-993d-11f0-b50d-c785d6db0d0e
```
This feature is defined in RFC-1070.
Related Jiras: [APPSEC-59279]
[APPSEC-59279]: https://datadoghq.atlassian.net/browse/APPSEC-59279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYz …
=> Add block ID to block & redirect action parameters & event
